- hosts: all
  become: yes
  tasks:
    - name: create the 'atsi' user
      user: name=atsi append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'atsi' to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=atsi key="{{item}}"
      with_file:
        - ./id_rsa.pub
