- hosts: master
  tasks:
   - name: Generate join command
     become: yes
     command: kubeadm token create --print-join-command
     register: join_command

   - name: Copy join command to local file
     local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"


- hosts: workers
  tasks:
   - name: start docker
     become: yes
     command: sudo service docker start

   - name: Copy the join command to server location
     copy: src=join-command dest=/tmp/join-command.sh mode=0777

   - name: Join the node to cluster
     command: sudo sh /tmp/join-command.sh
